### ISSUE TITLE
TypeError: umfpack_di_symbolic() missing 1 required positional argument: 'Info'

### ISSUE THREAD

**Issue by dahnlund** [scikit-umfpack/scikit-umfpack#98]
First time getting a successful installation with this package after the update 0.4.1, but I get this recurring error when I try to use spsolve. When running "pytest --pyargs scikits.umfpack" I get "TypeError: umfpack_di_symbolic() missing 1 required positional argument: 'Info'" in almost every test. This is a subset of the output:

self = <scikits.umfpack.tests.test_interface.TestSolvers testMethod=test_solve_int64_umfpack>

    @unittest.skipIf(_is_32bit_platform, reason="requires 64 bit platform")
    def test_solve_int64_umfpack(self):
        # Solve with UMFPACK: double precision, int64 indices
        a = _to_int64(self.a.astype('d'))
    
        b = self.b
>       x = um.spsolve(a, b)

/usr/local/lib/python3.11/site-packages/scikits/umfpack/tests/test_interface.py:71: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.11/site-packages/scikits/umfpack/interface.py:62: in spsolve
    x = UmfpackLU(A).solve(b)
/usr/local/lib/python3.11/site-packages/scikits/umfpack/interface.py:206: in __init__
    self.umf.numeric(A)
/usr/local/lib/python3.11/site-packages/scikits/umfpack/umfpack.py:555: in numeric
    self.symbolic(mtx)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <scikits.umfpack.umfpack.UmfpackContext object at 0x11112fd90>
mtx = <5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Column format>

    def symbolic(self, mtx):
        """
        Perform symbolic object (symbolic LU decomposition) computation for a given
        sparsity pattern.
        """
        self.free_symbolic()
    
        indx = self._getIndx(mtx)
    
        if not assumeSortedIndices:
            # row/column indices cannot be assumed to be sorted
            mtx.sort_indices()
    
        if self.isReal:
            status, self._symbolic\
>                   = self.funs.symbolic(mtx.shape[0], mtx.shape[1],
                                          mtx.indptr,
                                          indx,
                                          mtx.data,
                                          self.control, self.info)
E           TypeError: umfpack_dl_symbolic() missing 1 required positional argument: 'Info'

/usr/local/lib/python3.11/site-packages/scikits/umfpack/umfpack.py:522: TypeError
_________________ TestSolvers.test_solve_sparse_rhs __________________

self = <scikits.umfpack.tests.test_interface.TestSolvers testMethod=test_solve_sparse_rhs>

    def test_solve_sparse_rhs(self):
        # Solve with UMFPACK: double precision, sparse rhs
        a = self.a.astype('d')
        b = csc_matrix(self.b).T
>       x = um.spsolve(a, b)

/usr/local/lib/python3.11/site-packages/scikits/umfpack/tests/test_interface.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.11/site-packages/scikits/umfpack/interface.py:62: in spsolve
    x = UmfpackLU(A).solve(b)
/usr/local/lib/python3.11/site-packages/scikits/umfpack/interface.py:206: in __init__
    self.umf.numeric(A)
/usr/local/lib/python3.11/site-packages/scikits/umfpack/umfpack.py:555: in numeric
    self.symbolic(mtx)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <scikits.umfpack.umfpack.UmfpackContext object at 0x11128add0>
mtx = <5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Column format>

    def symbolic(self, mtx):
        """
        Perform symbolic object (symbolic LU decomposition) computation for a given
        sparsity pattern.
        """
        self.free_symbolic()
    
        indx = self._getIndx(mtx)
    
        if not assumeSortedIndices:
            # row/column indices cannot be assumed to be sorted
            mtx.sort_indices()
    
        if self.isReal:
            status, self._symbolic\
>                   = self.funs.symbolic(mtx.shape[0], mtx.shape[1],
                                          mtx.indptr,
                                          indx,
                                          mtx.data,
                                          self.control, self.info)
E           TypeError: umfpack_di_symbolic() missing 1 required positional argument: 'Info'

/usr/local/lib/python3.11/site-packages/scikits/umfpack/umfpack.py:522: TypeError
___________________ TestSolvers.test_solve_umfpack ___________________

**Comment by rishi-kulkarni** [comment]
Are you on Mac by any chance? I have the same error, but I can't reproduce on Linux.

**Comment by rishi-kulkarni** [comment]
My guess is that you have a much newer version of SuiteSparse installed - I can reproduce this on 7.3.1. Installing an older version, like the one installed in the CI pipeline (v5.10) clears this up. An easy way to install this on Mac is via conda-forge: https://anaconda.org/conda-forge/suitesparse.

CC @rc - it looks like the interface of these functions changed on SuiteSparse 7+. Unfortunately, the versions of SuiteSparse available via package repositories is all over the place - Brew offers 7.3.1, Macports offers 5.13.0, the CI installs 5.10.1 via apt. Might be worth a note in the README about explicitly supported SuiteSparse versions.

**Comment by dahnlund** [comment]
Yes, I have tried it on both 7.1.0 and later 7.3.1 (both installed via Brew on Mac). Might have to try an older version by source installation.

**Comment by DrTimothyAldenDavis** [comment]
I haven't changed the API to umfpack_di_symbolic; it's been the same since at least 2006 and probably earlier.  I just checked SuiteSparse v2.1.1 (the oldest copy I have on github) and umfpack_di_symbolic is the same there as it is in the current SuiteSparse 7.4.0.beta12 prerelease.

I have changed how the include files are provided; I used to have a set of files and a single top-level umfpack.h that included them all.  I now just have one file.  That might account for the difference you're seeing. But the contents have been very stable.

**Comment by rishi-kulkarni** [comment]
Yes, it's a little challenging to reproduce this, since the meson build file looks in a lot of places before looking in the user-specified nativefile. However, if you delete those other paths in the build file, it's a bit easier to test. This bug did indeed begin after the include file change.

**Comment by DrTimothyAldenDavis** [comment]
I'm close to releasing a stable SuiteSparse 7.4.0.  Its build system is much better now and some of these issues may be resolved when using that version.  Let me know if there's anything I can do to revise 7.4.0 to help resolve this issue.

**Comment by leuraph** [comment]
I've installed SuiteSparse version 7.4.0 via `brew` and scikit-umfpack version 0.4.1 via `pip`. Still, I do encounter the very same issue as stated above.

**Comment by bnavigator** [comment]
Here is the output of pip/meson-python compiling a wheel on openSUSE Linux with suitesparse 7.5.1 resulting in the same error above:

```
[   14s] + /usr/bin/python3.9 -mpip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build .
[   15s] Processing /home/abuild/rpmbuild/BUILD/scikit_umfpack-0.4.1
[   15s]   Preparing metadata (pyproject.toml): started
[   15s]   Running command Preparing metadata (pyproject.toml)
[   15s]   + meson setup /home/abuild/rpmbuild/BUILD/scikit_umfpack-0.4.1 /home/abuild/rpmbuild/BUILD/scikit_umfpack-0.4.1/.mesonpy-l1pyrepj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/abuild/rpmbuild/BUILD/scikit_umfpack-0.4.1/.mesonpy-l1pyrepj/meson-python-native-file.ini
[   16s]   The Meson build system
[   16s]   Version: 1.3.2
[   16s]   Source dir: /home/abuild/rpmbuild/BUILD/scikit_umfpack-0.4.1
[   16s]   Build dir: /home/abuild/rpmbuild/BUILD/scikit_umfpack-0.4.1/.mesonpy-l1pyrepj
[   16s]   Build type: native build
[   16s]   Project name: scikits.umfpack
[   16s]   Project version: 0.4.1
[   16s]   C compiler for the host machine: cc (gcc 13.2.1 "cc (SUSE Linux) 13.2.1 20240206 [revision 67ac78caf31f7cb3202177e6428a46d829b70f23]")
[   16s]   C linker for the host machine: cc ld.bfd 2.42.0.20240130-1
[   16s]   Host machine cpu family: x86_64
[   16s]   Host machine cpu: x86_64
[   16s]   Program python found: YES (/usr/bin/python3.9)
[   16s]   Program swig found: YES (/usr/bin/swig)
[   16s]   Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
[   16s]   Run-time dependency openblas found: YES 0.3.25
[   16s]   Run-time dependency umfpack found: YES 6.3.1
[   16s]   Compiler for C supports arguments -Wno-misleading-indentation: YES
[   16s]   Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
[   16s]   Run-time dependency python found: YES 3.9
[   16s]   Build targets in project: 2
[   16s] 
[   16s]   scikits.umfpack 0.4.1
[   16s] 
[   16s]     User defined options
[   16s]       Native files: /home/abuild/rpmbuild/BUILD/scikit_umfpack-0.4.1/.mesonpy-l1pyrepj/meson-python-native-file.ini
[   16s]       buildtype   : release
[   16s]       b_ndebug    : if-release
[   16s]       b_vscrt     : md
[   16s] 
[   16s]   Found ninja-1.11.1 at /usr/bin/ninja
[   16s]   + /usr/bin/ninja
[   17s]   [1/3] Generating scikits/umfpack/_umfpack_swig with a custom command
[   17s]   /usr/include/suitesparse/umfpack.h:86: Warning 202: Could not evaluate expression '!defined (SUITESPARSE__VERSION) || \
[   17s]       (SUITESPARSE__VERSION < SUITESPARSE__VERCODE(7,5,0))'
[   17s]   /usr/include/suitesparse/umfpack.h:86: Warning 202: Syntax error: expected operator
[   17s]   /usr/include/suitesparse/umfpack.h:91: Warning 202: Could not evaluate expression '!defined (AMD__VERSION) || \
[   17s]       (AMD__VERSION < SUITESPARSE__VERCODE(3,3,1))'
[   17s]   /usr/include/suitesparse/umfpack.h:91: Warning 202: Syntax error: expected operator
...
[   23s] Building wheels for collected packages: scikit-umfpack
[   23s]   Building wheel for scikit-umfpack (pyproject.toml): started
[   23s]   Running command Building wheel for scikit-umfpack (pyproject.toml)
[   23s]   Building wheel for scikit-umfpack (pyproject.toml): finished with status 'done'
[   23s]   Created wheel for scikit-umfpack: filename=scikit_umfpack-0.4.1-cp310-cp310-linux_x86_64.whl size=1586116 sha256=283004e5e9b87b57cf429c9165acc527f584b74920bf540bfb97097d095b6140
[   23s]   Stored in directory: /home/abuild/.cache/pip/wheels/cf/b2/e5/9a16e9a3cbab52c5928e5e83a61d092d7b1026915ba95ba42c
[   23s] Successfully built scikit-umfpack
...
[   35s] + pytest-3.9 --ignore=_build.python39 --ignore=_build.python310 --ignore=_build.python312 --ignore=_build.python311 -v --pyargs scikits.umfpack
[   35s] ============================= test session starts ==============================
[   35s] platform linux -- Python 3.9.18, pytest-7.4.4, pluggy-1.3.0 -- /usr/bin/python3.9
[   35s] cachedir: .pytest_cache
[   35s] rootdir: /home/abuild/rpmbuild/BUILD/scikit_umfpack-0.4.1
[   35s] configfile: pytest.ini
[   35s] collecting ... collected 21 items
...
[   36s] =================================== FAILURES ===================================
[   36s] _________________ TestSolvers.test_solve_complex_int64_umfpack _________________
[   36s] 
[   36s] self = <umfpack.tests.test_interface.TestSolvers testMethod=test_solve_complex_int64_umfpack>
[   36s] 
[   36s]     @unittest.skipIf(_is_32bit_platform, reason="requires 64 bit platform")
[   36s]     def test_solve_complex_int64_umfpack(self):
[   36s]         # Solve with UMFPACK: double precision complex, int64 indices
[   36s]         a = _to_int64(self.a.astype('D'))
[   36s]         b = self.b
[   36s] >       x = um.spsolve(a, b)
[   36s] 
[   36s] ../../BUILDROOT/python-scikit-umfpack-0.4.1-1.2.x86_64/usr/lib64/python3.9/site-packages/scikits/umfpack/tests/test_interface.py:55: 
[   36s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   36s] ../../BUILDROOT/python-scikit-umfpack-0.4.1-1.2.x86_64/usr/lib64/python3.9/site-packages/scikits/umfpack/interface.py:62: in spsolve
[   36s]     x = UmfpackLU(A).solve(b)
[   36s] ../../BUILDROOT/python-scikit-umfpack-0.4.1-1.2.x86_64/usr/lib64/python3.9/site-packages/scikits/umfpack/interface.py:206: in __init__
[   36s]     self.umf.numeric(A)
[   36s] ../../BUILDROOT/python-scikit-umfpack-0.4.1-1.2.x86_64/usr/lib64/python3.9/site-packages/scikits/umfpack/umfpack.py:555: in numeric
[   36s]     self.symbolic(mtx)
[   36s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   36s] 
[   36s] self = <scikits.umfpack.umfpack.UmfpackContext object at 0x7fe39c6b89d0>
[   36s] mtx = <5x5 sparse matrix of type '<class 'numpy.complex128'>'
[   36s] 	with 9 stored elements in Compressed Sparse Column format>
[   36s] 
[   36s]     def symbolic(self, mtx):
[   36s]         """
[   36s]         Perform symbolic object (symbolic LU decomposition) computation for a given
[   36s]         sparsity pattern.
[   36s]         """
[   36s]         self.free_symbolic()
[   36s]     
[   36s]         indx = self._getIndx(mtx)
[   36s]     
[   36s]         if not assumeSortedIndices:
[   36s]             # row/column indices cannot be assumed to be sorted
[   36s]             mtx.sort_indices()
[   36s]     
[   36s]         if self.isReal:
[   36s]             status, self._symbolic\
[   36s]                     = self.funs.symbolic(mtx.shape[0], mtx.shape[1],
[   36s]                                           mtx.indptr,
[   36s]                                           indx,
[   36s]                                           mtx.data,
[   36s]                                           self.control, self.info)
[   36s]         else:
[   36s]             real, imag = mtx.data.real.copy(), mtx.data.imag.copy()
[   36s]             status, self._symbolic\
[   36s] >                   = self.funs.symbolic(mtx.shape[0], mtx.shape[1],
[   36s]                                           mtx.indptr,
[   36s]                                           indx,
[   36s]                                           real, imag,
[   36s]                                           self.control, self.info)
[   36s] E           TypeError: umfpack_zl_symbolic() missing 1 required positional argument: 'Info'
[   36s] 
[   36s] ../../BUILDROOT/python-scikit-umfpack-0.4.1-1.2.x86_64/usr/lib64/python3.9/site-packages/scikits/umfpack/umfpack.py:530: TypeError
```

Haven't tried updating to suitesparse 7.6 yet

**Comment by j-bowhay** [comment]
I am also experiencing this on error on 7.6.1-1

**Comment by cmutel** [comment]
@leuraph Could you describe how you got it working? Did you have `SuiteSparse` in a conda environment and `scikit-umfpack` in a normal venv? How did pip know where the SuiteSparse libraries were?

**Comment by minrk** [comment]
just encountered this trying to update the conda-forge package, since conda-forge is now on suitesparse 7.7.

FWIW, the missing argument appears to be `Symbolic` in the signature:

```
def umfpack_di_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info) -> int
```

where it's called expecting `(n_row, n_col, Ap, Ai, Ax, Control, Info) -> (int, Symbolic)`. 

I don't know enough about how swig works, but it seems the `**Symbolic/**Numeric` output variables aren't detected as output variables, as intended by OPAQUE_ARGOUT [here](https://github.com/scikit-umfpack/scikit-umfpack/blob/ce77944bce003a29771ae07be182af348c3eadce/scikits/umfpack/umfpack.i#L234-L253). Given the comment about order being important and interspersed `%apply` and include, I assume the fact that umfpack.h is now a single header means the OPAQUE_ARGOUT is no longer applied to the expected definitions (or OPAQUE_ARGINOUT is applied _more_ places than expected, I'm not sure).

There also appear to be changes re: SuiteSparse_long -> int64_t that need updating in the swig file, but I'm also not sure about that, since the type is the same, just the declaration.

**Comment by bentrainer** [comment]
encountered the same problem on suitesparse==7.8.2 from conda-forge, any clues on how to solve this?

**Comment by carlosal1015** [comment]
Same error, with the example of spsolve documentation, suitesparse 7.8.3-1, NumPy 2.1.2 with [latest patch](https://github.com/scikit-umfpack/scikit-umfpack/pull/104) .

```python
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import spsolve

A = csc_matrix([[3, 2, 0], [1, -1, 0], [0, 5, 1]], dtype=float)
B = csc_matrix([[2, 0], [-1, 0], [2, 0]], dtype=float)
x = spsolve(A, B)
```

```
Traceback (most recent call last):
  File "/tmp/main.py", line 6, in <module>
    x = spsolve(A, B)
        ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 302, in spsolve
    Afactsolve = factorized(A)
                 ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 592, in factorized
    umf.numeric(A)
  File "/usr/lib/python3.12/site-packages/scikits/umfpack/umfpack.py", line 555, in numeric
    self.symbolic(mtx)
  File "/usr/lib/python3.12/site-packages/scikits/umfpack/umfpack.py", line 522, in symbolic
    = self.funs.symbolic(mtx.shape[0], mtx.shape[1],
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: umfpack_dl_symbolic() missing 1 required positional argument: 'Info'
```

**Comment by JohnDN90** [comment]
Using hints from the [post by minrk](https://github.com/scikit-umfpack/scikit-umfpack/issues/98#issuecomment-2155098551) and the [post by DrTimothyAldenDavis](https://github.com/scikit-umfpack/scikit-umfpack/issues/98#issuecomment-1869516012), I was able to get scikit-umfpack working with SuiteSparse 7.9.0.

My method is a somewhat messy workaround and the scikit-umfpack source still needs to be updated to be compatible with the newer SuiteSparse versions, but this works for the time being.  Details of how I did it can be found in [this repo](https://github.com/JohnDN90/scikit-umfpack_workaround).

**Comment by tstoltzfus** [comment]
@JohnDN90 Your messy workaround worked for me on an M2 Mac mini with OSX 14.6 and an M1 Macbook pro running OSX 15.3.  Thanks!

**Comment by carlosal1015** [comment]
I tried but no luck
```
==> Extracting sources...
  -> Creating working copy of scikit-umfpack-0.4.1 git repo...
Cloning into 'scikit-umfpack-0.4.1'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
patching file scikits/umfpack/umfpack.i
==> Starting build()...
* Building wheel...
+ meson setup /build/python-scikit-umfpack/src/scikit-umfpack-0.4.1 /build/python-scikit-umfpack/src/scikit-umfpack-0.4.1/.mesonpy-ejbt4ft3 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/build/python-scikit-umfpack/src/scikit-umfpack-0.4.1/.mesonpy-ejbt4ft3/meson-python-native-file.ini
The Meson build system
Version: 1.7.0
Source dir: /build/python-scikit-umfpack/src/scikit-umfpack-0.4.1
Build dir: /build/python-scikit-umfpack/src/scikit-umfpack-0.4.1/.mesonpy-ejbt4ft3
Build type: native build
Project name: scikits.umfpack
Project version: 0.4.1
C compiler for the host machine: cc (gcc 14.2.1 "cc (GCC) 14.2.1 20250207")
C linker for the host machine: cc ld.bfd 2.44
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python found: YES (/usr/bin/python)
Program swig found: YES (/usr/bin/swig)
Found pkg-config: YES (/usr/bin/pkg-config) 2.3.0
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency openblas found: NO (tried pkgconfig and cmake)
Library openblas found: NO
Library blas found: YES
Library cblas found: YES
Run-time dependency umfpack found: YES 6.3.5
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
Run-time dependency python found: YES 3.13
Build targets in project: 2

scikits.umfpack 0.4.1

  User defined options
    Native files: /build/python-scikit-umfpack/src/scikit-umfpack-0.4.1/.mesonpy-ejbt4ft3/meson-python-native-file.ini
    b_ndebug    : if-release
    b_vscrt     : md
    buildtype   : release

Found ninja-1.12.1 at /usr/bin/ninja
+ /usr/bin/ninja                                
[1/3] Generating scikits/umfpack/_umfpack_swig with a custom command
FAILED: scikits/umfpack/_umfpack_wrap.c scikits/umfpack/_umfpack.py 
/usr/bin/swig -python -I/usr/include/suitesparse -I/usr/local/include -I/usr/include/suitesparse -o scikits/umfpack/_umfpack_wrap.c -outdir scikits/umfpack ../scikits/umfpack/umfpack.i
/usr/include/suitesparse/umfpack.h:86: Warning 202: Could not evaluate expression '!defined (SUITESPARSE__VERSION) || \
    (SUITESPARSE__VERSION < SUITESPARSE__VERCODE(7,8,0))'
/usr/include/suitesparse/umfpack.h:86: Warning 202: Use of undefined function-like macro
/usr/include/suitesparse/umfpack.h:91: Warning 202: Could not evaluate expression '!defined (AMD__VERSION) || \
    (AMD__VERSION < SUITESPARSE__VERCODE(3,3,3))'
/usr/include/suitesparse/umfpack.h:91: Warning 202: Use of undefined function-like macro
../scikits/umfpack/umfpack.i:217: Error: Unable to find 'umfpack_solve.h'
../scikits/umfpack/umfpack.i:218: Error: Unable to find 'umfpack_defaults.h'
../scikits/umfpack/umfpack.i:219: Error: Unable to find 'umfpack_triplet_to_col.h'
../scikits/umfpack/umfpack.i:220: Error: Unable to find 'umfpack_col_to_triplet.h'
../scikits/umfpack/umfpack.i:221: Error: Unable to find 'umfpack_transpose.h'
../scikits/umfpack/umfpack.i:222: Error: Unable to find 'umfpack_scale.h'
../scikits/umfpack/umfpack.i:224: Error: Unable to find 'umfpack_report_symbolic.h'
../scikits/umfpack/umfpack.i:225: Error: Unable to find 'umfpack_report_numeric.h'
../scikits/umfpack/umfpack.i:226: Error: Unable to find 'umfpack_report_info.h'
../scikits/umfpack/umfpack.i:227: Error: Unable to find 'umfpack_report_control.h'
../scikits/umfpack/umfpack.i:239: Error: Unable to find 'umfpack_symbolic.h'
../scikits/umfpack/umfpack.i:240: Error: Unable to find 'umfpack_numeric.h'
../scikits/umfpack/umfpack.i:248: Error: Unable to find 'umfpack_free_symbolic.h'
../scikits/umfpack/umfpack.i:249: Error: Unable to find 'umfpack_free_numeric.h'
../scikits/umfpack/umfpack.i:269: Error: Unable to find 'umfpack_get_lunz.h'
../scikits/umfpack/umfpack.i:304: Error: Unable to find 'umfpack_get_numeric.h'
ninja: build stopped: subcommand failed.

ERROR Backend subprocess exited when trying to invoke build_wheel
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /home/carlosal1015/chroot/carlosal1015/build
```

**Comment by josephlr** [comment]
> I tried but no luck

It looks like the `UMFPACK_MAIN_VERSION` check in `umfpack.i` isn't triggering in your version. Looking at the line numbers it seems like you might be building against an older version of `umfpack.i`, as `umfpack_solve.h` is on line 221 on the current HEAD (and in 0.4.1).
https://github.com/scikit-umfpack/scikit-umfpack/blob/9ba622ac90350e621e84e78ed03a23d1d47807bd/scikits/umfpack/umfpack.i#L221

I can also confirm that cloning `https://aur.archlinux.org/python-scikit-umfpack` and then running `makepkg -si` works on my Arch Linux system and installs the package with only an unrelated warning about deprecated numpy APIs. So I don't think updating the package is necessary or will fix this issue.

Similarly, the installing via `pip` using the master branch of this repo with https://github.com/scikit-umfpack/scikit-umfpack/pull/103 applied, works on both on Arch Linux and on macOS (provided `pkgconf` is installed).

However in all three cases (`pip` on macOS, `pip` on Arch Linux, `python-scikit-umfpack` on Arch Linux), any use of `spsolve` fails at _runtime_ with:
```
umfpack_di_symbolic() missing 1 required positional argument: 'Info'
```
indicating that this is entirely a problem with `scikit-umfpack`'s SWIG code (as others have noted above).

**Comment by josephlr** [comment]
I was able to get something working in #106 based on @JohnDN90's work.

It removes all of the brittle order-dependent SWIG stuff, and fixes a few other bugs noted by @JohnDN90. With suitesparse 7.10, it now seems to properly build and run (installing on macos also requires #103). All the tests pass, and I was able to solve some simple equations with `spsolve`.

Note that PR is not complete as it breaks the `*_free_*` methods. I just commented them out in `umfpack.py` for now, but there should be a way to fix the bindings to work in just that case.
